INSERT INTO (nome, cognome, email, data_nascita)
VALUES
('Francesco','Ferrari','francescoferrari@gmail.com', '2010-09-21'),
('Leonardo','Russo','leonardorusso@gmail.com'),
('Alessandro','Esposito','lucaviola@gmail.com'),
('Lorenzo','Bianchi','geronimorosso@gmail.com'),
('Mattia','Romano','mattiaromano@gmail.com'),
('Andrea','Colombo','andreacolombo@gmail.com'),
('Riccardo','Ricci','ricardoricci@gmail.com'),
('Tommaso','Marino','tommasomarino@gmail.com'),
('Edoardo','Greco','edoardogreco@gmail.com'),
('Sofia','Bruno','sofiabruno@gmail.com'),
('Alice','Gallo','alicegallo@gmail.com'),
('Giulia','Conti','giuliaconti@gmail.com'),
('Emma','Mancini','emmamancini@gmail.com');
('Ginevra','Costa','ginevracosta@gmail.com'),
('Giulia','Giordano','giuliagiordano@gmail.com'),
('Giulia','Rizzo','giuliarizzo@gmail.com'),
('Giorgia','Lombardi','giorgialombardi@gmail.com'),
('Greta','Moretti','gretamoretti@gmail.com'),
('Beatrice','Barberi','beatricebarberi@gmail.com'),
('Anna','Fontana','annafontana@gmail.com'),
('Martina','Santoro','martinasantoro@gmail.com'),
('Mattia','Mariani','mattiamariani@gmail.com'),